Modified deployment instructions to use shared fabrikam-worklaod repo
mspnp/microservices-reference-implementation pull request #214
Opened 2021-05-07 16:45 UTC by magrande

2021-05-07 20:02 UTC, ferantivero requested changes
promptly blocking this one til we are done with the advanced one.

2021-05-28 16:10 UTC, v-fearam commented on deployment.md
> +export RESOURCE_GROUP=rg-shipping-microservices
The constants set are ok or they are here by mistake?

2021-05-28 16:14 UTC, v-fearam approved these changes

2021-05-28 16:26 UTC, ckittel approved these changes
Looks pretty well aligned to the other, but I'll defer to @ferantivero for anything else that should be addressed.

2021-05-31 13:01 UTC, ferantivero requested changes

2021-05-31 13:06 UTC, v-fearam commented on azuredeploy-prereqs.json
> -{
about CI/CD, we agree to delete that from Basic. Neil confirms that he has deleted the references (Chad asked Neil about that last week), so next step is deleting from the repo.

2021-06-01 15:37 UTC, ferantivero commented on azuredeploy-prereqs.json
> -{
@magrande please let's get rid of the following section from the `deployment.md`:

### Optional: Set up automated CI/CD for dev, test, qa and production with Azure DevOps

Additionally delete `yml` + `json` related to CI/CD from https://github.com/mspnp/fabrikam-dronedelivery-workload (it doesn't need to take precedence).

2021-06-01 15:37 UTC, ferantivero approved these changes

2021-06-01 15:44 UTC, merged