Microservices basic scenario - Replaced FlexVol by CSI driver
mspnp/microservices-reference-implementation pull request #216
Opened 2021-06-03 20:08 UTC by magrande

2021-06-03 20:09 UTC, magrande commented on deployment.md
> +# Install the aks-preview extension
@ckittel  I'm not sure if I the aks-preview extension is needed, can you confirm ?

2021-06-03 20:29 UTC, ckittel commented on deployment.md
> +# Install the aks-preview extension
you should be able to remove these instructions.  You don't use it here.  You'd only need it if you planed on adding it to the cluster via CLI

2021-06-03 20:33 UTC, ckittel requested changes

2021-06-03 20:33 UTC, ckittel commented on deployment.md
> +export EXTERNAL_INGEST_DNS_NAME="${RESOURCE_GROUP}-$RANDOM-ing" && \
```suggestion
export EXTERNAL_INGEST_DNS_NAME="${RESOURCE_GROUP}-${RANDOM}-ing" && \
```

2021-06-03 20:33 UTC, ckittel commented on deployment.md
> +export EXTERNAL_INGEST_DNS_NAME="${RESOURCE_GROUP}-$RANDOM-ing" && \
Also, is that a thing?  Just wanted to make sure that both $RANDOM is set and `-ing` is what you wanted at the end

2021-06-03 21:00 UTC, magrande commented on deployment.md
> +export EXTERNAL_INGEST_DNS_NAME="${RESOURCE_GROUP}-$RANDOM-ing" && \
This is the result:

rg-shipping-microservices-17665-ing

So "ing" stands for ingestion. Here is a  problem, the name's length matters, if it's too long the certificate generation step fails. So I had to use "ing" instead of "ingestion", that's not so fancy, I could remove it or I could eliminate the resource group name.

2021-06-03 21:03 UTC, magrande commented on deployment.md
> +# Install the aks-preview extension
All of them or just the aks-preview extension ?

2021-06-04 13:03 UTC, ckittel commented on deployment.md
> +# Install the aks-preview extension
just the installing of the preview extension

2021-06-04 13:04 UTC, ckittel commented on deployment.md
> +export EXTERNAL_INGEST_DNS_NAME="${RESOURCE_GROUP}-$RANDOM-ing" && \
ah, that's fine then, thanks for explaining.  Just still the `{...}` suggestion from above.

2021-06-04 13:45 UTC, magrande commented on deployment.md
> +# Install the aks-preview extension
Removed !

2021-06-04 13:45 UTC, magrande commented on deployment.md
> +export EXTERNAL_INGEST_DNS_NAME="${RESOURCE_GROUP}-$RANDOM-ing" && \
Done !

2021-06-04 15:03 UTC, ckittel approved these changes
🚀

2021-06-04 15:13 UTC, merged