Microservices RA - Charts update as part of helm3 upgrade
mspnp/microservices-reference-implementation pull request #219
Opened 2021-06-25 17:57 UTC by magrande

2021-06-25 18:35 UTC, ckittel reviewed
I'm just surprised at the removal of the actual service files, but guessing there is just something I'm not aware of here...  I'm not a Helm expert nor super familiar on this workload, so /shrug

2021-06-25 18:35 UTC, ckittel commented on charts/dronescheduler/envs/dronescheduler-prod/templates/dronescheduler-service.yaml
> -{{ end }}
Where are these files going now?  The resources themselves don't matter any more? Probably just a knowledge gap on my side.

2021-06-25 20:55 UTC, magrande commented on charts/dronescheduler/envs/dronescheduler-prod/templates/dronescheduler-service.yaml
> -{{ end }}
We no longer need the environments (prod, qa, staging)... I'm just leaving "dev" and leaving the dependency on that one. I could also not even have evironments at all, and so in that case we wouldn't need any dependency, I need to spend one cycle with Fernando on that decision.

2021-06-25 20:56 UTC, ckittel commented on charts/dronescheduler/envs/dronescheduler-prod/templates/dronescheduler-service.yaml
> -{{ end }}
My point was that the manifest files were all found under `prod` -- yet those got deleted.  Do you not need the actual manifest files anymore?

2021-06-25 21:03 UTC, magrande commented on charts/dronescheduler/envs/dronescheduler-prod/templates/dronescheduler-service.yaml
> -{{ end }}
I did and end to end deployment from scratch and it was successful, weird !  I'll double check why this happened

2021-06-25 21:14 UTC, ckittel commented on charts/dronescheduler/envs/dronescheduler-prod/templates/dronescheduler-service.yaml
> -{{ end }}
Cool, looking forward to learning about it.  Like I said, might be a large misunderstanding on my side. Seeking to understand :)

2021-06-28 14:19 UTC, magrande commented on charts/dronescheduler/envs/dronescheduler-prod/templates/dronescheduler-service.yaml
> -{{ end }}
@ckittel I Talked to Fernando about this, and the manifest file was intended to be used when we used to have blue green deployments via CI/CD. Since we eliminated the automated deployment from the RA we don't need it anymore.

2021-06-28 14:25 UTC, ckittel commented on charts/dronescheduler/envs/dronescheduler-prod/templates/dronescheduler-service.yaml
> -{{ end }}
Ah, that explains it :)  Thank you.

2021-06-28 14:34 UTC, ckittel approved these changes
I caught myself up on the helm2 -> helm3 changes, and what you have here seems to be aligned.  So going to mark approved.  Thanks!

2021-06-28 15:30 UTC, ferantivero requested changes
so far so good @magrande just a few comments

2021-06-28 15:30 UTC, ferantivero commented on charts/delivery/Chart.yaml
> +    version: ">= 0.0.1"
```suggestion
    version: "v0.1.0"
    condition: envs.dev
```

please let's propagate this change to the rest of the charts.

2021-06-28 15:30 UTC, ferantivero commented on charts/delivery/Chart.yaml
> +apiVersion: v2
please let's all add

```yaml
type: application
home: https://docs.microsoft.com/azure/architecture/reference-architectures/microservices/aks
sources:
  - https://github.com/mspnp/microservices-reference-implementation
```

2021-06-28 15:30 UTC, ferantivero commented on charts/delivery/Chart.yaml
> +apiVersion: v2
I was pretty sure that `Helm3` made required to pass the `namespace` where it needs to be deployed. It wasn't using one by default anymore. Also there were some change in the params order. It means that some change were needed at the deployment level. Could you please confirm that? 

Please let's ensure we are testing using helm3.

2021-06-28 19:23 UTC, ferantivero commented on charts/delivery/Chart.yaml
> +apiVersion: v2
sorry it wasn't required to pass the namespace but to create that beforehand. 

Also, please let's ensure we work with a clean working copy since `helm3` dependent charts also required to firstly create packages updating its dependencies, and then install from package instead. There, it also impact the deployment steps.

2021-06-29 21:05 UTC, ferantivero commented on charts/delivery/Chart.yaml
> +    version: ">= 0.0.1"
I think this change needs to be replicated on every `chart.yaml` if I am not mistaken.

2021-06-29 21:20 UTC, magrande commented on charts/delivery/Chart.yaml
> +    version: ">= 0.0.1"
You are right, just updated the rest of the charts and tested.

2021-06-30 14:36 UTC, ferantivero approved these changes
nicely done @magrande - LGTM 🚀

2021-06-30 14:37 UTC, merged