Microservices RA - Add more secrets to keyvault and CSI store (ingestion service)
mspnp/microservices-reference-implementation pull request #220
Opened 2021-08-06 14:27 UTC by magrande

2021-08-06 14:49 UTC, ckittel requested changes
One question to see if something is actually needed (I'm not sure, hence the question), and also a two similar "practice what we preach" suggestions to make the ARM template adhere to our recommendations better. 

Otherwise, I didn't see anything else that jumped out at me.  w00t!

2021-08-06 14:49 UTC, ckittel commented on charts/ingestion/templates/ingestion-deploy.yaml
> +          readOnly: true
Why did we need to mount this?  Is that required just to populate the secrets?  I assumed just referencing the volume would have been sufficient.

2021-08-06 14:49 UTC, ckittel commented on azuredeploy.json
> +        "scope": "[concat(subscription().id, '/resourceGroups/',  resourceGroup().name, '/providers/Microsoft.ManagedIdentity/userAssignedIdentities/',parameters('ingestionIdName'))]"
```suggestion
        "scope": "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', parameters('ingestionIdName'))]"
```

I know the rest of them were the way you had it as well, but we should rarely build resource IDs via the `concat()` function, that's a discouraged practice.

2021-08-06 14:49 UTC, ckittel commented on azuredeploy.json
> +      "value": "[concat(subscription().id, '/resourceGroups/',resourceGroup().name,'/providers/Microsoft.ManagedIdentity/userAssignedIdentities/',parameters('ingestionIdName'))]",
```suggestion
      "value": "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', parameters('ingestionIdName'))]",
```

I know the rest of them were the way you had it as well, but we should rarely build resource IDs via the `concat()` function, that's a discouraged practice.

2021-08-07 22:55 UTC, magrande commented on charts/ingestion/templates/ingestion-deploy.yaml
> +          readOnly: true
I'm not sure I was just copying what was done in Workflow. Do you think it worths the effort deleting it and testing ?

2021-08-09 12:45 UTC, ckittel commented on charts/ingestion/templates/ingestion-deploy.yaml
> +          readOnly: true
workflow used it because it loaded those literally from the directory, IIRC.  Would probably be good if we taught our learners what is necessary to do here.  Would it be hard to remove and test?

2021-08-09 13:16 UTC, ckittel commented on charts/ingestion/templates/ingestion-deploy.yaml
> +          readOnly: true
Sounds required.  Good to know.

2021-08-09 13:16 UTC, ckittel approved these changes

2021-08-09 13:28 UTC, merged