Microservices RA - Added ingress TLS secrets to keyvault - delivery service
mspnp/microservices-reference-implementation pull request #224
Opened 2021-09-13 17:05 UTC by magrande

2021-09-13 17:16 UTC, ckittel requested changes
Mostly just an implementation question/clarification for me.

2021-09-13 17:16 UTC, ckittel commented on charts/delivery/templates/delivery-deploy.yaml
> +              key: ingress-tls-crt
These used to be in a k8s `Secret`, how did the workload get access to these before?  Anything need to change about that process? They weren't being mounted before as env variables.  Is the workload trying to access them directly?  I'm a bit confused on where the "second part" of the change is here.

2021-09-13 17:16 UTC, ckittel commented on charts/delivery/templates/delivery-deploy.yaml
> +              key: ingress-tls-crt
I see that the secret name is referenced in the ingress controller as `tlsSecretName`, right?  Why do they need to be mounted as part of the delivery workload here?

2021-09-14 12:38 UTC, magrande commented on deployment.md
> +      key: ingestion-ingress-tls.key
@ckittel  I'm not sure this is the name of the key, Can you help me figuring out where it's being used ?

2021-09-14 13:42 UTC, ckittel commented on deployment.md
> +      key: ingestion-ingress-tls.key
Responded on call. The names you're looking for are in the secrets files that you deleted as part of this PR.

2021-09-15 18:16 UTC, ckittel requested changes

2021-09-15 18:16 UTC, ckittel commented on deployment.md
>  export INGRESS_TLS_SECRET_NAME=ingestion-ingress-tls
How is this so low in the instructions?  You needed to use this value both in the helm chart right below, but also when you created the `SecretProviderClass`.  Looks like you are calling those secrets the wrong name though, `ingestion-secrets` -- hard coded.

2021-09-15 19:35 UTC, ckittel requested changes

2021-09-15 19:35 UTC, ckittel commented on deployment.md
> +  - secretName: "${INGRESS_TLS_SECRET_NAME}"
Why did this change now?  We now have two `SecretProviderClass` instances managing the exact same secret.

2021-09-15 19:36 UTC, ckittel commented on deployment.md
>  export INGRESS_TLS_SECRET_NAME=ingestion-ingress-tls
Moved out, resolving.  Opened another item below for a side effect of your last change.

2021-09-15 20:15 UTC, ckittel approved these changes
Assuming you're able to complete your testing, this change looks good.  Marking approved, just let me know when testing is complete.

2021-09-16 00:33 UTC, magrande commented
> Assuming you're able to complete your testing, this change looks good. Marking approved, just let me know when testing is complete.

@ckittel  I had to do some "subtle" change in the secretsprovider class, after that, Ingestion service started to work properly.

2021-09-16 00:34 UTC, merged