Update RI
mspnp/microservices-reference-implementation pull request #235
Opened 2023-11-08 20:28 UTC by v-fearam

Bicep. 
Enable workload  identity. 
Readme Updates.

2024-01-15 18:10 UTC, ferantivero requested changes

2024-01-16 11:34 UTC, v-fearam commented on azuredeploy.bicep
> +        mode: 'System'
I created a task for the future. My idea is as soon as possible have a version working again, and to do improvement later on.

2024-01-16 11:45 UTC, v-fearam commented on charts/delivery/values.yaml
> +  tenantId:
It is true, good catch, tenantId is not needed on dronescheduler

2024-01-16 11:46 UTC, v-fearam commented on charts/delivery/values.yaml
> +  tenantId:
yes, It is needed. 
charts\delivery\templates\delivery-secret-provider.yaml
tenantId: {{ .Values.identity.tenantId }}

dronescheduler doesn't have SecretProviderClass

2024-01-16 12:12 UTC, v-fearam commented on charts/ingestion/templates/ingestion-ingress.yaml
>    {{- if .tls }}
The readme is for TLS 
in deployment.md
```
helm package charts/ingestion/ -u && \
helm install ingestion-v0.1.0-dev ingestion-v0.1.0.tgz \
     --set image.tag=0.1.0 \
     --set image.repository=ingestion \
     --set dockerregistry=$ACR_SERVER \
     --set identity.clientid=$INGESTION_ID_CLIENT_ID \
     --set identity.serviceAccountName=ingestion-sa-v0.1.0 \
     --set identity.tenantId=$TENANT_ID \
     --set keyVaultName=$INGESTION_KEYVAULT_NAME \
     --set ingress.hosts[0].name=$EXTERNAL_INGEST_FQDN \
     --set ingress.hosts[0].serviceName=ingestion \
     --set ingress.hosts[0].tls=true \
     --set ingress.hosts[0].tlsSecretName=$INGRESS_TLS_SECRET_NAME \
     **--set ingress.tls=true \**
     --set ingress.class=nginx \
     --set secrets.queue.keyname=IngestionServiceAccessKey \
     --set secrets.queue.name=${INGESTION_QUEUE_NAME} \
     --set secrets.queue.namespace=${INGESTION_QUEUE_NAMESPACE} \
     --set reason="Initial deployment" \
     --set tags.dev=true \
     --namespace backend-dev \
     --dependency-update
```

2024-01-16 12:17 UTC, v-fearam commented on charts/workflow/values.yaml
> +  delivery: http://delivery-v010/api/Deliveries/
A) It is not possible, you don't know which version like to work each dependency
For example, v010 delivery, v251 package, and done v100, it is a perfect combination. 
B) I can move as parameter, this is a parameter with default value, you can overwrite passing on command line.  I will move to the readme file.

2024-01-16 12:27 UTC, v-fearam commented on charts/ingestion/templates/ingestion-ingress.yaml
> +      paths:
done

2024-01-16 12:27 UTC, v-fearam commented on charts/workflow/values.yaml
> +  delivery: http://delivery-v010/api/Deliveries/
done

2024-01-16 13:47 UTC, v-fearam commented on charts/delivery/templates/delivery-ingress.yaml
> +    secretName: {{ .tlsSecretName }}
No, if you don't like. 
tlsSecretName  is a deploy parameter, you could  use the name you like for your version. You could use the same or not.
```
helm package charts/ingestion/ -u && \
helm install ingestion-v0.1.0-dev ingestion-v0.1.0.tgz \
     --set image.tag=0.1.0 \
     --set image.repository=ingestion \
     --set dockerregistry=$ACR_SERVER \
     --set identity.clientid=$INGESTION_ID_CLIENT_ID \
     --set identity.serviceAccountName=ingestion-sa-v0.1.0 \
     --set identity.tenantId=$TENANT_ID \
     --set keyVaultName=$INGESTION_KEYVAULT_NAME \
     --set ingress.hosts[0].name=$EXTERNAL_INGEST_FQDN \
     --set ingress.hosts[0].serviceName=ingestion \
     --set ingress.hosts[0].tls=true \
     **--set ingress.hosts[0].tlsSecretName=ingestion-ingress-tls \**
     --set ingress.tls=true \
     --set ingress.class=nginx \
     --set secrets.queue.keyname=IngestionServiceAccessKey \
     --set secrets.queue.name=${INGESTION_QUEUE_NAME} \
     --set secrets.queue.namespace=${INGESTION_QUEUE_NAMESPACE} \
     --set reason="Initial deployment" \
     --set tags.dev=true \
     --namespace backend-dev \
     --dependency-update
``` 
And, the SecretProviderClass is versioning, and you can use the same name in a different key vault. 
```

###################################################################################################
# Ingestion Secret Provider Class - CSI Driver
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ingestion-secrets-csi-akv-{{ $svcversion }}
  namespace: backend-dev
spec:
  provider: azure
  secretObjects:
  **- secretName: ingestion-ingress-tls**
    type: Opaque
    data:
    - objectName: Ingestion-Ingress-Tls-Key
      key: tls.key
    - objectName: Ingestion-Ingress-Tls-Crt
      key: tls.crt
  - secretName: ingestion-secrets
    type: Opaque
    data:
    - objectName: Queue--Key
      key: queue-keyvalue
    - objectName: ApplicationInsights--InstrumentationKey
      key: appinsights-ikey
  parameters:
    usePodIdentity: "false"
    **clientID: {{ .Values.identity.clientid }}
    keyvaultName: {{ .Values.keyVaultName }}**
    objects:  |
      array:
        - |
          objectName: Queue--Key
          objectAlias: Queue--Key
          objectType: secret
        - |
          objectName: ApplicationInsights--InstrumentationKey
          objectAlias: ApplicationInsights--InstrumentationKey
          objectType: secret
        - |
          objectName: Ingestion-Ingress-Tls-Key
          objectAlias: Ingestion-Ingress-Tls-Key
          objectType: secret
        - |
          objectName: Ingestion-Ingress-Tls-Crt
          objectAlias: Ingestion-Ingress-Tls-Crt
          objectType: secret
    tenantId: {{ .Values.identity.tenantId }}
---
```

2024-01-16 13:53 UTC, v-fearam commented on charts/dronescheduler/templates/dronescheduler-identity.yaml
> +kind: ServiceAccount
done

2024-01-16 13:57 UTC, v-fearam commented on charts/ingestion/templates/ingestion-secret-provider.yaml
> +          objectName: Queue--Key
I created a task for the future. My idea is as soon as possible have a version working again, and to do improvement later on.

2024-01-16 14:01 UTC, v-fearam commented on azuredeploy.bicep
> +    addonProfiles: {
I created a task for the future. My idea is as soon as possible have a version working again, and to do improvement later on.

2024-01-16 14:05 UTC, v-fearam commented on azuredeploy.bicep
> +    linuxProfile: {
done

2024-01-16 16:43 UTC, v-fearam commented on azuredeploy.bicep
> +    addonProfiles: {
added

2024-01-17 15:34 UTC, ferantivero approved these changes
LGTM

2024-01-17 16:12 UTC, merged